#ifndef FORGE_CONFIG_VERSION_H
#define FORGE_CONFIG_VERSION_H

#include "macro.hpp"

#define FORGE_VERSION_MAJOR 1
#define FORGE_VERSION_MINOR 1
#define FORGE_VERSION_PATCH 0

#define FORGE_VERSION               \
    FORGE_XSTR(FORGE_VERSION_MAJOR) \
    "." FORGE_XSTR(FORGE_VERSION_MINOR) "." FORGE_XSTR(FORGE_VERSION_PATCH)

#endif